# Build artifact image
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

# Build args
ARG ASPNETCORE_ENVIRONMENT=Development \
    PORT=80

# Environment variables
ENV ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT \
    ASPNETCORE_URLS=http://+:$PORT \
    PATH="${PATH}:/root/.dotnet/tools" \
    PORT=$PORT

WORKDIR /src
COPY app/ /src/app
COPY db/ /src/db
COPY scripts/ /src/scripts
COPY tests/ /src/tests

RUN dotnet restore /src/tests/tests.csproj
RUN dotnet restore /src/app/lucky-music.csproj
RUN dotnet publish /src/app/lucky-music.csproj -c Release -o /src/app/out
RUN dotnet dev-certs https --trust
RUN dotnet tool install -g dotnet-reportgenerator-globaltool

EXPOSE $PORT

ENTRYPOINT dotnet run --urls $ASPNETCORE_URLS --project /src/app/